### ISSUE TITLE
Error: The magic method __callStatic() must have public visibility and be static

### ISSUE THREAD

**Issue by DuckThom** [infernobass7/laravel-print-node#5]
https://github.com/infernobass7/laravel-print-node/blob/54cdf332b10fee0bf2ee7ccebe6f28550b115029/src/Entity.php#L88

This line is producing an error, it should be:

```
public static function __callStatic($method, $parameters)
```

**Comment by nikolay-shapoval** [comment]
can you please merge this fix with master?
